#########################################################################
# Title:         UnionFS: Docker Tasks                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Docker | Create override directory"
  file: "path=/etc/systemd/system/docker.service.d state=directory mode=0775"

- name: "Docker | Import override file"
  template: "src=override.conf.js2 dest=/etc/systemd/system/docker.service.d/override.conf force=yes mode=0775"

- name: "Docker | Systemd daemon-reload"
  systemd: name=docker state=reloaded daemon_reload=yes

- name: "Docker | Restart docker service"
  systemd: name=docker state=restarted

- name: "Docker | Wait for 30 seconds before commencing"
  wait_for:
    timeout: 30
