#########################################################################
# Title:         Cloudbox: UnionFS Role                                 #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Existing Setup

- name: Legacy Tasks
  import_tasks: "subtasks/legacy.yml"

- name: Service Tasks
  include_tasks: "subtasks/service.yml"
  loop_control:
    loop_var: outer_item
  loop:
    - "unionfs.service"
    - "mergerfs.service"

- name: Mount Tasks
  import_tasks: "subtasks/mount.yml"

# New Setup

- name: Basic Tasks
  import_tasks: "subtasks/basic.yml"

- name: MergerFS Tasks
  import_tasks: "subtasks/mergerfs.yml"
  when: (mounts.unionfs | lower == "mergerfs")

- name: UnionFS Tasks
  import_tasks: "subtasks/unionfs.yml"
  when: (mounts.unionfs | lower == "unionfs")

- name: Docker Tasks
  import_tasks: "subtasks/docker.yml"

# Start Containers

- name: Container Tasks
  import_tasks: "subtasks/container.yml"
  when: ('mounts' in ansible_run_tags) or ('mounts_override' in ansible_run_tags)
