#########################################################################
# Title:         Cloudbox: NZBHydra2 Role                               #
# Author(s):     Desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare
  vars:
    subdomain: nzbhydra2

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: nzbhydra2
    state: absent

- name: Create nzbhydra2 directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/nzbhydra2

- name: Check if nzbhydra.yml exists
  stat:
    path: "/opt/nzbhydra2/nzbhydra.yml"
  register: nzbhydra2_yml

- name: Create and start container
  docker_container:
    name: nzbhydra2
    image: hotio/suitarr
    pull: yes
    published_ports:
      - "127.0.0.1:5076:5076"
    env:
      APP: "nzbhydra2"
      VERSION: "unstable"
      BACKUP: "no"
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "nzbhydra2.{{domain}}"
      VIRTUAL_PORT: 5076
      LETSENCRYPT_HOST: "nzbhydra2.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nzbhydra2:/config"
      - "/opt/nzbhydra/hydra:/nzbhydra1"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - nzbhydra2
    state: started

- name: Wait for nzbhydra.yml to be created
  wait_for:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    state: present
  when: not nzbhydra2_yml.stat.exists

- name: "Wait for 10 seconds before stopping nzbhydra2 container"
  wait_for:
    timeout: 10
  when: not nzbhydra2_yml.stat.exists

- name: Stop container to customize nzbhydra.yml
  docker_container:
    name: nzbhydra2
    image: hotio/suitarr
    state: stopped
  when: not nzbhydra2_yml.stat.exists

- name: Update auth settings
  lineinfile:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - {regexp: '(authType:)\s".*?"', line: '  \1 "FORM"'}
    - {regexp: '(restrictAdmin:)\s.*', line: '  \1 true'}
    - {regexp: '(restrictDetailsDl:)\s.*', line: '  \1 true'}
    - {regexp: '(restrictIndexerSelection:)\s.*', line: '  \1 true'}
    - {regexp: '(restrictSearch:)\s.*', line: '  \1 true'}
    - {regexp: '(restrictStats:)\s.*', line: '  \1 true'}
    - {regexp: '(users:)\s?.*', line: '  \1'}
  when: not nzbhydra2_yml.stat.exists

- name: Add login settings
  lineinfile:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    insertafter: 'users:'
    line: "{{ item.line }}"
    state: present
  with_items:
    - {line: '    password: "{{passwd}}"'}
    - {line: '    username: "{{user}}"'}
    - {line: '    showIndexerSelection: true'}
    - {line: '    maySeeStats: true'}
    - {line: '    maySeeDetailsDl: true'}
    - {line: '  - maySeeAdmin: true'}
  when: not nzbhydra2_yml.stat.exists

- name: Increase JVM memory
  lineinfile:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - {regexp: '(xmx:)\s?.*', line: '  \1 512'}
  when: (not nzbhydra2_yml.stat.exists) and ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int >= 16)

- name: Add downloaders section
  lineinfile:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - {regexp: '(downloaders:)\s?.*', line: '  \1'}
  when: not nzbhydra2_yml.stat.exists

- name: Add NZBGet downloader
  lineinfile:
    path: "/opt/nzbhydra2/nzbhydra.yml"
    insertafter: 'downloaders:'
    line: "{{ item.line }}"
    state: present
  with_items:
    - {line: '    password: "{{passwd}}"'}
    - {line: '    username: "{{user}}"'}
    - {line: '    url: "http://nzbget:6789"'}
    - {line: '    downloaderType: "NZBGET"'}
    - {line: '    nzbAddingType: "UPLOAD"'}
    - {line: '    name: "NZBGet"'}
    - {line: '    iconCssClass: ""'}
    - {line: '    enabled: true'}
    - {line: '    downloadType: "NZB"'}
    - {line: '    defaultCategory: null'}
    - {line: '  - apiKey: null'}
  when: not nzbhydra2_yml.stat.exists

- name: Start container to apply changes
  docker_container:
    name: nzbhydra2
    state: started
  when: not nzbhydra2_yml.stat.exists
