#########################################################################
# Title:         ruTorrent -  Settings Tasks                            #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/rutorrent-autodl                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
## Checks

- name: Wait for 'rtorrent.rc' to be created
  wait_for:
    path: "/opt/rutorrent/rtorrent/rtorrent.rc"
    state: present

- name: Wait for 'php.ini' to be created
  wait_for:
    path: "/opt/rutorrent/php/php.ini"
    state: present

- name: Wait for 'nginx.conf' to be created
  wait_for:
    path: "/opt/rutorrent/nginx/nginx.conf"
    state: present

- name: Wait for 'plugins.ini' to be created
  wait_for:
    path: "/opt/rutorrent/rutorrent/settings/plugins.ini"
    state: present

- name: "Wait for 10 seconds before stopping rutorrent container"
  wait_for:
    timeout: 10

- name: Stop container
  docker_container:
    name: rutorrent
    state: stopped

## Import ruTorrent Static Settings Tasks

- name: ruTorrent Static Settings Tasks
  include_tasks: "rutorrent_settings_static.yml"
  when: (not rtorrent_rc.stat.exists)

## Import ruTorrent Dynamic Settings Tasks

- name: ruTorrent Dynamic Settings Tasks
  include_tasks: "rutorrent_settings_dynamic.yml"

- name: Start container
  docker_container:
    name: rutorrent
    state: started
