#########################################################################
# Title:         Cloudbox: ruTorrent Role -  Settings Tasks             #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  horjulf/rutorrent-autodl                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get public IP Address
  uri:
    url: http://checkip.amazonaws.com
    return_content: yes
  register: public_ip_lookup

- name: Set 'public_ip'
  set_fact:
    public_ip: "{{ public_ip_lookup.content | trim }}"

- name: Set 'network.local_address.set'
  lineinfile:
    path: "/opt/rutorrent/rtorrent/rtorrent.rc"
    regexp: '^network\.local_address\.set\s*=.*'
    line: 'network.local_address.set = {{ public_ip }}'
    state: present

- name: Add comment for 'network.local_address.set'
  lineinfile:
    path: "/opt/rutorrent/rtorrent/rtorrent.rc"
    insertbefore: '^network\.local_address\.set\s*=.*'
    line: "# The ip address reported to the tracker"
    state: present
