#########################################################################
# Title:         System: Set Time Zone                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove '/etc/localtime'
  file:
    path: "/etc/localtime"
    state: absent

- name: Fetch time zone
  uri:
    url: http://ip-api.com/line?fields=timezone
    return_content: yes
  register: timezone_response
  when: (system.timezone|lower == 'auto') or (not system.timezone)

- name: Set time zone
  timezone:
    name: "{{ (timezone_response.content | trim) if ((system.timezone|lower == 'auto') or (not system.timezone)) else (system.timezone) }}"
