#########################################################################
# Title:         System: Fix Timezone Link                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Fetch stats on '/etc/localtime'
  stat:
    path: "/etc/localtime"
  register: localtime

- name: Fix time zone link when target is a folder
  block:

  - name: Fetch stats on link target
    stat:
      path: "{{ localtime.stat.lnk_target }}"
    register: target

  - name: Set time zone
    block:

    - name: Fetch time zone
      uri:
        url: http://ip-api.com/line?fields=timezone
        return_content: yes
      register: timezone_response

    - name: Set time zone
      timezone:
        name: "{{ timezone_response.content | trim }}"

    when: (target.stat.isdir is defined) and (target.stat.isdir)

  when: (localtime.stat.islnk is defined) and (localtime.stat.islnk)
