#########################################################################
# Title:         Cloudbox: Kernel Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set default 'reboot_is_necessary' variable
  set_fact:
    reboot_is_necessary: false

- name: Preinstall task
  include_tasks: "subtasks/preinstall.yml"
  when: ('preinstall' in ansible_run_tags)

- name: "Kernel: Hetzner tasks"
  include_tasks: "subtasks/hetzner.yml"

- name: "Kernel: Cron task"
  include_tasks: "subtasks/cron.yml"

- name: "Kernel: Script task"
  include_tasks: "subtasks/script.yml"

- name: "Kernel: Update task"
  include_tasks: "subtasks/update.yml"

- name: "Kernel: Headers task"
  include_tasks: "subtasks/headers.yml"

- name: "Kernel: Restart After Changes"
  include_tasks: "subtasks/restart.yml"
  when: (reboot_is_necessary) and
    (not continuous_integration)

- name: "Kernel: Checks task"
  include_tasks: "subtasks/checks.yml"