---
- name: Add DNS Record to Cloudflare
  cloudflare_dns:
    account_api_token: "{{cloudflare_api_token}}"
    account_email: "{{email}}"
    zone: "{{domain}}"
    state: present
    proxied: no
    type: A
    value: "{{ansible_default_ipv4.address}}"
    record: organizr
  when: not(
      (cloudflare_api_token is undefined)
      or
      (cloudflare_api_token is none)
      or
      (cloudflare_api_token | trim == '')
    )

- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: organizr
    state: absent

- name: Create organizr directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/organizr

- name: Create and start container
  docker_container:
    name: organizr
    image: "lsiocommunity/organizr"
    pull: yes
    published_ports:
      - "127.0.0.1:7421:80"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "organizr.{{domain}}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "organizr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/organizr:/config"
    networks:
      - name: cloudbox
        aliases:
          - organizr
    restart_policy: always
    state: started
