#########################################################################
# Title:         Cloudbox: NZBGet Settings Sub Tasks                    #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/suitarr                                          #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Wait for nzbget.conf to be created
  wait_for:
    path: "/opt/nzbget/app/nzbget.conf"
    state: present

- name: "Wait for 10 seconds before stopping nzbget container"
  wait_for:
    timeout: 10

- name: Stop container to customize nzbget.conf
  docker_container:
    name: nzbget
    state: stopped

- name: Change downloads directory
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^MainDir\s?='
    line: 'MainDir=/downloads/nzbget'
    state: present

- name: Change scripts directory
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^ScriptDir\s?='
    line: 'ScriptDir=/scripts'
    state: present

- name: Rename Movies category
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^Category1.Name\s?='
    line: 'Category1.Name=radarr'
    state: present

- name: Rename TV category
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^Category2.Name\s?='
    line: 'Category2.Name=sonarr'
    state: present

- name: Rename Music category
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^Category3.Name\s?='
    line: 'Category3.Name=lidarr'
    state: present

- name: Remove default Username
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^ControlUsername\s?='
    line: 'ControlUsername='
    state: present

- name: Remove default Password
  lineinfile:
    path: "/opt/nzbget/app/nzbget.conf"
    regexp: '^ControlPassword=\s?='
    line: 'ControlPassword='
    state: present

- name: Start container to apply changes
  docker_container:
    name: nzbget
    state: started
