#########################################################################
# Title:            Cloudbox: Sonarr Role                               #
# Author(s):        l3uddz, desimaniac                                  #
# URL:              https://github.com/cloudbox/cloudbox                #
# Docker Image(s):  hotio/sonarr,                                       #
#                   andrewkhunn/suitarr_mp4_automator                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: sonarr
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: sonarr
    state: absent

- name: Remove darkerr config
  file:
    path: "/opt/nginx-proxy/vhost.d/sonarr.{{ domain }}_location"
    state: absent
  when: not (darkerr.enable | default(false,true))

- name: Suitarr Migration Tasks
  import_tasks: "subtasks/suitarr_migration.yml"

- name: Create sonarr directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - /opt/sonarr

- name: Add darkerr config
  copy:
    src: "darkerr-nginx-conf"
    dest: "/opt/nginx-proxy/vhost.d/sonarr.{{ domain }}_location"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0664
    force: yes
  when: (darkerr.enable | default(false,true))

- name: Set 'suitarr_image' variable
  set_fact:
    suitarr_image: "{{ (sickbeard_mp4_automator | default(false,true)) | ternary('andrewkhunn/suitarr_mp4_automator:sonarr','hotio/sonarr') }}"

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/sonarr:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/TV:/tv"

- name: Create and start container
  docker_container:
    name: sonarr
    image: "{{ suitarr_image }}"
    pull: yes
    published_ports:
      - "127.0.0.1:8989:8989"
    env:
      VERSION: "{{ sonarr.version }}"
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr.{{ domain }}"
      VIRTUAL_PORT: 8989
      LETSENCRYPT_HOST: "sonarr.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and sickbeard_mp4_automator and dev_dri.stat.exists) | default(false) else omit }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - sonarr
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
