#########################################################################
# Title:         Remote: Service Tasks                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Service | Check if '{{ outer_item }}' exists"
  stat:
    path: "/etc/systemd/system/{{ outer_item }}"
  register: service_file

- name: "Service | Tasks for '{{ outer_item }}'"
  block:

  - name: "Service | Stop and disable existing '{{ outer_item }}'"
    systemd:
      name: "{{ outer_item }}"
      state: stopped
      enabled: no

  - name: "Service | Update ownership in existing '{{ outer_item }}'"
    ini_file:
      path: "/etc/systemd/system/{{ outer_item }}"
      section: Service
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      state: present
      no_extra_spaces: yes
    loop:
      - { option: 'User', value: "{{ user }}" }
      - { option: 'Group', value: "{{ user }}" }

  - name: Rclone Cache | Enable cache in 'rclone.conf'
    blockinfile:
      path: "/home/{{ user }}/.config/rclone/rclone.conf"
      state: absent
      marker: "### {mark} CLOUDBOX - RCLONE CACHE MOUNT ###"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    when: outer_item == "rclone_cache.service"

  # if applicable
  - name: "Service | Update 'rc-addr' in existing '{{ outer_item }}'"
    replace:
      path: "/etc/systemd/system/{{ outer_item }}"
      regexp: "rc-addr=localhost:[0-9]*"
      replace: 'rc-addr=localhost:5572'

  - name: "Service | Remove 'RemainAfterExit=yes' '{{ outer_item }}'"
    lineinfile:
      path: "/etc/systemd/system/{{ outer_item }}"
      regexp: '^RemainAfterExit\=yes'
      state: absent

  - name: "Service | Systemd daemon-reload"
    systemd: daemon_reload=yes

  when: (service_file.stat.exists)
