#########################################################################
# Title:         Cloudbox: Pre-Tasks - Variables Task                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set 'use_nzbs'"
  set_fact:
    use_nzbs: "{{ true if (nzbs_downloads_path is defined|default(false,true)) else false }}"

- name: "Set 'use_torrents'"
  set_fact:
    use_torrents: "{{ true if (torrents_downloads_path is defined|default(false,true)) else false }}"
