#########################################################################
# Title:         Cloudbox: Remote Role                                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

# Sanity Check
- name: Sanity Check Tasks
  import_tasks: "subtasks/sanity_check.yml"

# Stop Containers

- name: Container Tasks
  import_tasks: "subtasks/container.yml"
  when: ('mounts' in ansible_run_tags) or ('mounts_override' in ansible_run_tags)

# Existing Setup

- name: Legacy Tasks
  import_tasks: "subtasks/legacy.yml"

- name: Service Tasks
  include_tasks: "subtasks/service.yml"
  loop_control:
    loop_var: outer_item
  loop:
    - "plexdrive4.service"
    - "plexdrive5.service"
    - "rclone_vfs.service"
    - "rclone_vfs_primer.service"
    - "rclone_vfs_primer.timer"

- name: Mount Tasks
  import_tasks: "subtasks/mount.yml"

# New Setup

- name: Fuse Tasks
  import_tasks: "subtasks/fuse.yml"

- name: Basic Tasks
  import_tasks: "subtasks/basic.yml"

- name: Plexdrive Tasks
  block:

  - name: Plexdrive 4 Tasks
    import_tasks: "subtasks/plexdrive4.yml"
    when: ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int < 8)

  - name: Plexdrive 5 Tasks
    import_tasks: "subtasks/plexdrive5.yml"
    when: ((ansible_memory_mb.real.total/1024)|round(0,'ceil')|int >= 8)

  when: (mounts.remote | lower == 'plexdrive')

- name: Plexdrive4  Tasks
  import_tasks: "subtasks/plexdrive4.yml"
  when: (mounts.remote | lower == 'plexdrive4')

- name: Plexdrive 5 Tasks
  import_tasks: "subtasks/plexdrive5.yml"
  when: (mounts.remote | lower == 'plexdrive5')

- name: Rclone VFS Tasks
  import_tasks: "subtasks/rclone_vfs.yml"
  when: (mounts.remote | lower == 'rclone_vfs')
