#########################################################################
# Title:         Cloudbox: Sonarr4K Role                                #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  hotio/sonarr                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare
  vars:
    subdomain: sonarr4k

- name: Stop and remove any existing container
  docker_container:
    name: sonarr4k
    state: absent

- name: Remove darkerr config
  file:
    path: "/opt/nginx-proxy/vhost.d/sonarr4k.{{ domain }}_location"
    state: absent
  when: not (darkerr.enable | default(false,true))

- name: Suitarr Migration Tasks
  import_tasks: "subtasks/suitarr_migration.yml"

- name: Create sonarr4k directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user }} group={{ user }}"
  with_items:
    - /opt/sonarr4k

- name: Add darkerr config
  copy:
    src: "darkerr-nginx-conf"
    dest: "/opt/nginx-proxy/vhost.d/sonarr4k.{{ domain }}_location"
    owner: "{{user}}"
    group: "{{user}}"
    mode: 0664
    force: yes
  when: (darkerr.enable | default(false,true))

- name: Set default_volumes variable
  set_fact:
    default_volumes:
      - "/opt/sonarr4k:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/TV:/tv"

- name: Create and start container
  docker_container:
    name: sonarr4k
    image: "hotio/sonarr"
    pull: yes
    published_ports:
      - "127.0.0.1:8990:8989"
    env:
      VERSION: "{{ suitarr.version }}"
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      MONO_TLS_PROVIDER: legacy
      VIRTUAL_HOST: "sonarr4k.{{ domain }}"
      VIRTUAL_PORT: 8989
      LETSENCRYPT_HOST: "sonarr4k.{{ domain }}"
      LETSENCRYPT_EMAIL: "{{ email }}"
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - sonarr4k
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
