#########################################################################
# Title:         Cloudbox: System Handler                               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Update Locales
  shell: dpkg-reconfigure --frontend noninteractive locales
