#########################################################################
# Title:         Cloudbox: Cloudbox Settings Sub Tasks                  #
# Author(s):     L3uddz, Desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.rocks          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if '{{item}}' exists."
  stat:
    path: "{{playbook_dir}}/{{item}}"
  register: file

- name: "Copy '{{item}}.default' to '{{item}}'."
  copy:
    src: "{{playbook_dir}}/{{item}}.default"
    dest: "{{playbook_dir}}/{{item}}"
    owner: "{{cloudbox_yml.stat.uid}}"
    group: "{{cloudbox_yml.stat.gid}}"
    mode: 0664
    force: yes
  when: not file.stat.exists

# Hash Check
- name: "Get stats on '{{item}}.default' for hash check."
  stat:
    path: "{{playbook_dir}}/{{item}}.default"
  register: file_default
  when: "item == 'settings.yml'"

# Hash Check
- name: "Ensure '{{item}}' does not match '{{item}}.default'."
  assert:
    that:
      - file.stat.exists
      - file.stat.checksum != file_default.stat.checksum
    msg: "Please edit your '{{item}}' file. For more info, see the Wiki page 'Install: Settings'."
  when: "item == 'settings.yml'"

- name: "Run 'settings-updater.py' for '{{item}}'."
  script: "roles/settings/files/settings-updater.py '{{playbook_dir}}' '{{item}}.default' '{{item}}'"
  become: yes
  become_user: "{{cloudbox_yml.stat.pw_name}}"
  register: settings_updater
  failed_when: settings_updater.rc == 1

- name: "Check 'settings-updater.py' run status for errors with updating 'adv_settings.yml'."
  debug: msg="The script 'settings_updater.py' exited with an error when updating 'adv_settings.yml. Check 'settings-updater.log' for details."
  when: "(item == 'adv_settings.yml') and (settings_updater.rc == 1)"

- name: "Check 'settings-updater.py' run status for new settings in 'adv_settings.yml'."
  debug: msg="The script 'settings_updater.py' added new settings to 'adv_settings.yml'. Check 'settings-updater.log' for details."
  when: "(item == 'adv_settings.yml') and (settings_updater.rc == 2)"

- name: "Check 'settings-updater.py' run status for errors with updating 'settings.yml'."
  fail: msg="The script 'settings_updater.py' exited with an error when updating 'settings.yml'. Check 'settings-updater.log' for details."
  when: "(item == 'settings.yml') and (settings_updater.rc == 1)"

- name: "Check 'settings-updater.py' run status for new settings in 'settings.yml'."
  fail: msg="The script 'settings_updater.py' added new settings to 'settings.yml'. Check 'settings-updater.log' for details."
  when: "(item == 'settings.yml') and (settings_updater.rc == 2)"
