---
- name: Install ruamel.yaml
  pip:
    name: ruamel.yaml
    version: 0.15.35
    executable: pip3

- name: Check if 'settings.yml' exists
  stat:
    path: "{{playbook_dir}}/settings.yml"
  register: settings_yml

- name: "Get user"
  set_fact: temp_user={{ playbook_dir.split('/')[2] }}
  when: settings_yml.stat.exists == False

- name: Get group
  shell: "id -gn {{ temp_user }}"
  register: temp_group
  when: settings_yml.stat.exists == False

- name: Copy 'settings.yml.default' to 'settings.yml'
  copy:
    src: "{{ playbook_dir }}/settings.yml.default"
    dest: "{{ playbook_dir }}/settings.yml"
    owner: "{{ temp_user }}"
    group: "{{ temp_group.stdout }}"
    mode: 0664
    force: yes
  when: settings_yml.stat.exists == False

- name: Get stats on 'defaults.yml'
  stat:
    path: "{{playbook_dir}}/settings.yml.default"
  register: settings_yml_default

- name: Exit when new 'settings.yml' is made
  assert:
    that:
      - settings_yml.stat.exists
      - settings_yml.stat.checksum != settings_yml_default.stat.checksum
    msg: "Please edit your 'settings.yml' file. For more info, see the Wiki page: 'Configuring Settings'."

- name: Run 'settings-updater.py'
  script: roles/settings/files/settings-updater.py "{{playbook_dir}}"
  register: settings_updater

- name: Check 'settings-updater.py' run status
  fail: msg="The script 'settings_updater.py' exited with an error. Check `settings-updater.log` for details why."
  when: settings_updater.rc < 2
